# Generated by Django 4.2.5 on 2023-10-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='developer_id',
            new_name='id',
        ),
    ]
